/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function replaceText(original: string, pattern: string, replacement: string): string
export class CliUtils {
  static clear(): void
  static build(): void
}
export class FsUtils {
  static rmdir(path: string): boolean | null
  static mkdir(path: string): boolean | null
  static readdir(path: string): Array<string>
  static write(path: string, contents: string): boolean
  static read(path: string): string
  static isDir(path: string): boolean | null
  static isFile(path: string): boolean | null
}
export class PathUtils {
  static basename(path: string, ext?: string | undefined | null): string
  static extname(path: string): string | null
}
