/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function rmDir(path: string): boolean | null
export function mkDir(path: string): boolean | null
export function isDir(path: string): boolean | null
export function isFile(path: string): boolean | null
export function readdir(path: string): Array<string>
export function extname(path: string): string | null
export function basename(path: string, ext?: string | undefined | null): string
export function replaceText(original: string, pattern: string, replacement: string): string
