/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function rmDir(path: string): boolean | null
export function replaceText(original: string, pattern: string, replacement: string): string
